### ISSUE TITLE
No module named 'dataclasses'

### ISSUE THREAD

**Issue by thefeiter** [PhilippRigoll/POSM#4]
Hey there!

First of all, this editor is a very good idea!!

I have tried to run it by 

```
git clone https://github.com/PhilippRigoll/POSM.git
python3 setup.py develop
POSM
```

But I am getting:
```
Traceback (most recent call last):
  File "/usr/local/bin/POSM", line 11, in <module>
    load_entry_point('POSM', 'console_scripts', 'POSM')()
  File "/home/marvin/.local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 490, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/home/marvin/.local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2859, in load_entry_point
    return ep.load()
  File "/home/marvin/.local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2450, in load
    return self.resolve()
  File "/home/marvin/.local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2456, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/home/marvin/apps/POSM/POSM/main.py", line 12, in <module>
    from POSM.ElementsLoader.ElementsLoader import ElementsLoader
  File "/home/marvin/apps/POSM/POSM/ElementsLoader/ElementsLoader.py", line 10, in <module>
    from POSM.ElementsLoader import Node
  File "/home/marvin/apps/POSM/POSM/ElementsLoader/Node.py", line 5, in <module>
    from POSM.utils import calc
  File "/home/marvin/apps/POSM/POSM/utils/calc.py", line 6, in <module>
    from dataclasses import dataclass
ModuleNotFoundError: No module named 'dataclasses'
```

I would love to get any help running it, since I am interested in co-developing.
I am not sure, if my python knowledge is sufficient, but I would like to try and fiddle around.

**Comment by thefeiter** [comment]
Well, the `dataclasses` requirement is missing in `setup.py`.
Thats it for now...
